require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.bufferline"
require "user.nvim-tree"
require "user.autopairs"
require "user.treesitter"
require "user.comment"
require "user.toggleterm"
require "user.gitsign"
require "user.harpoon"
require "user.treesitter-context"
require "user.leap"
require "user.dap-python"
-- require "user.dap_setup"

